server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  redis:
    host: 192.168.31.27
    port: 6379
    database: 0
    timeout: 20000
    jedis:
      pool:
        max-active: 0
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: 192.168.31.27
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 0
zuul:
  #  sensitiveHeaders: "*"
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
    connection-request-timeout-millis: 20000
hystrix:
  command:
    default:
      execution:
        isolation:
#          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 80000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error
loginFilter:
  ignoreUris: /user/user/login, /user/user/register