server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 20000
    jedis:
      pool:
        max-active: 0
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
zuul:
  #  sensitiveHeaders: "*"
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    connection-request-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
  shareSecurityContext: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug
loginFilter:
  ignoreUris: /user/user/login, /user/user/register
management:
  endpoints:
    web:
      exposure:
        include: /actuator/hystrix.stream