spring:
  profiles:
    active: dev
  application:
    name: api-gateway
  messages:
    basename: i18n/messages
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  cloud:
    config:
      discovery:
        enabled: false
        service-id: config-server
      override-none: false
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
eureka:
  instance:
    prefer-ip-address: true
zuul:
  SendErrorFilter.error.disable: true
  sensitiveHeaders: "*"
  routes:
    authentication-server: /auth-server/**
    user-server: /user-server/**
    tweet-server: /tweet-server/**
    search-server: /search-server/**
    mail-server: /mail-server/**
jwt:
  header: authorization
  headerPrefix: Bearer
  secret: 6AJvUN7UaP0sqkT0
  expiration: 604800