spring:
  messages:
    basename: i18n/messages
zuul:
  SendErrorFilter.error.disable: true
  routes:
    authenticate-server: /auth/**
    user-server: /user/**
    tweet-server: /tweet/**
    search-server: /search/**
    mail-server: /mail/**