server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESSES}
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: root
    password: 12345678
    virtual-host: /
  sleuth:
    enabled: false
  zipkin:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 80000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error
    com.scott.neptune: error
