server:
  port: 8767
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 20000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 12345678
    virtual-host: /
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eager-load:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug
    com.scott.neptune: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
