server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESSES}
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  redis:
    host: ${SERVER_HOST}
    port: 6379
    database: 0
    timeout: 20000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: ${SERVER_HOST}
    port: 5672
    username: root
    password: 12345678
    virtual-host: /
  sleuth:
    enabled: false
  zipkin:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 80000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error
    com.scott.neptune: error
