server:
  port: 8767
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  rabbitmq:
    host: localhost
    port: 5672
    username: scott
    password: 12345678
minio:
  endpoint: http://127.0.0.1:9000
  access-key: scott
  secret-key: 12345678
  bucket: neptune-blog
folders:
  userAvatarSm: /userAvatar/sm
  userAvatarMd: /userAvatar/md
  postImageSm: /post/sm
  postImageOrigin: /post/origin