server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  rabbitmq:
    host: serverhost
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 0
minio:
  endpoint: http://serverhost:9000
  access-key: scott
  secret-key: 12345678
  bucket: neptune-blog
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 80000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true
    clients: user
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error
    com.scott.neptune: error
file:
  tempFolder: /neptune_files
folders:
  userAvatarSm: /userAvatar/sm
  userAvatarMd: /userAvatar/md
  postImageSm: /post/sm
  postImageOrigin: /post/origin