server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  rabbitmq:
    host: localhost
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 0
minio:
  endpoint: http://localhost:9000
  access-key: scott
  secret-key: 12345678
  bucket: neptune-blog
folders:
  userAvatarSm: /userAvatar/sm
  userAvatarMd: /userAvatar/md
  postImageSm: /post/sm
  postImageOrigin: /post/origin
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error