server:
  port: 8767
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  rabbitmq:
    host: localhost
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
minio:
  endpoint: http://localhost:9000
  access-key: scott
  secret-key: 12345678
  bucket: neptune-blog
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eager-load:
    enabled: true
    clients: user
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug
folders:
  userAvatarSm: /userAvatar/sm
  userAvatarMd: /userAvatar/md
  postImageSm: /post/sm
  postImageOrigin: /post/origin
file:
  avatars:
    -
      sizeType: 1
      height: 50
      width: 50
    -
      sizeType: 2
      height: 200
      width: 200
    -
      sizeType: 3
      height: 500
      width: 500
  tempFolder: neptune_files
  avatarExtensionName: png