spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
feign:
  hystrix:
    enabled: true
file:
  avatar:
    extensionName: png
    sizes:
      -
        sizeType: 1
        height: 50
        width: 50
      -
        sizeType: 2
        height: 200
        width: 200
      -
        sizeType: 3
        height: 500
        width: 500