server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  rabbitmq:
    host: 192.168.31.27
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 0
minio:
  endpoint: http://192.168.31.27:9000
  access-key: scott
  secret-key: 12345678
  bucket: neptune-blog
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 80000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true
    clients: user
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error
folders:
  userAvatarSm: /userAvatar/sm
  userAvatarMd: /userAvatar/md
  postImageSm: /post/sm
  postImageOrigin: /post/origin
file:
  avatars:
    small:
      sizeType: 1
      height: 50
      width: 50
    normal:
      sizeType: 2
      height: 200
      width: 200
    large:
      sizeType: 3
      height: 500
      width: 500
  tempFolder: neptune_files
  avatarExtensionName: png