server:
  port: 8080
spring:
  rabbitmq:
    host: serverhost
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 0
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error