server:
  port: 8769
spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug