server:
  port: 8769
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug
    com.scott.neptune: debug