server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.31.27:3306/db_neptune_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: scott
    password: 12345678
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  rabbitmq:
    host: 192.168.31.27
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 20000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  eager-load:
    enabled: true
    clients: user, file
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error