server:
  port: 8080
spring:
  sleuth:
    sampler:
      probability: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 20000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  eager-load:
    enabled: true
    clients: post, file
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error