server:
  port: 8772
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  eager-load:
    enabled: true
    clients: user, post, file
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug
    com.scott.neptune: debug