server:
  port: 8080
spring:
  rabbitmq:
    host: serverhost
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 80000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true
    clients: user, post, file
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error