server:
  port: 8080
spring:
  redis:
    host: serverhost
    port: 6379
    database: 0
    timeout: 20000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: serverhost
    port: 5672
    username: scott
    password: 12345678
  sleuth:
    sampler:
      probability: 0
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 80000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true
    clients: user, post, file
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error
    com.scott.neptune: error