server:
  port: 8772
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 60000
  eager-load:
    enabled: true
    clients: post, file
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug