spring:
  messages:
    basename: i18n/messages
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
feign:
  hystrix:
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml,mapper/*.xml
  type-aliases-package: com.scott.neptune
  check-config-location: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.scott.neptune
  global-config:
    db-column-underline: false
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
  pageSize: 30
label: Created by Scott Lau